// A generated document, drawn: the standard layout every document shares. Title, number, and date top left; the
// client's branding top right; who it's for; the body; and a footer that traces it. Not a page (no catalog entry).
import type { ReactNode } from 'react';
import { Pin } from '../../site/kit';
import { cx } from '../../lib/cx';
import './artifacts.css';

const P = ({ n, pins }: { n: number; pins?: boolean }) => (pins ? <Pin n={n} className="dc-pin" /> : null);

export function Doc({ title, meta, to, children, foot = 'Generated by Loans OS · 28 Sep 2026, 9:14 AM', pins, small, className }: {
  title: string; meta: ReactNode[]; to?: ReactNode; children: ReactNode; foot?: string; pins?: boolean; small?: boolean; className?: string;
}) {
  return (
    <div className={cx('dc', small && 'sm', className)}>
      <div className="dc-head">
        <div className="dc-rel"><P n={1} pins={pins} /><b className="dc-title">{title}</b>{meta.map((m, i) => <span key={i}>{m}</span>)}</div>
        <div className="dc-brand dc-rel"><P n={2} pins={pins} /><i className="dc-mark">ML</i><b>Metro Lending</b><span>3F Ayala Center, Cebu City</span><span>TIN 008-221-904-000</span></div>
      </div>
      {to && <div className="dc-to dc-rel"><P n={3} pins={pins} />{to}</div>}
      <div className="dc-body dc-rel"><P n={4} pins={pins} />{children}</div>
      <div className="dc-foot dc-rel"><P n={6} pins={pins} /><span>Metro Lending · Cebu City · hello@metrolending.ph · (032) 410 2200</span><span>{foot} · Page 1 of 1</span></div>
    </div>
  );
}

/** Rows of a document table, with an optional total row. */
export function Lines({ head, rows, total, className }: { head: string[]; rows: ReactNode[][]; total?: ReactNode[]; className?: string }) {
  // The last column, and any headed ₱, holds amounts: right-aligned, so the figures line up.
  const r = (j: number) => (j === head.length - 1 || head[j].startsWith('₱') ? 'r' : undefined);
  return (
    <table className={cx('dc-tbl', className)}>
      <thead><tr>{head.map((h, i) => <th key={i} className={r(i)}>{h}</th>)}</tr></thead>
      <tbody>{rows.map((row, i) => <tr key={i}>{row.map((c, j) => <td key={j} className={r(j)}>{c}</td>)}</tr>)}</tbody>
      {total && <tfoot><tr>{total.map((c, j) => <td key={j} className={r(j)}>{c}</td>)}</tr></tfoot>}
    </table>
  );
}
