import { Section, Demo, Rules, Avoid, When, Btn, Pill } from '../../site/kit';
import { Frame } from '../shell/shell-kit';
import { H } from '../shell/places-kit';
import '../records/foundations.css';
import '../shell/shell.css';
import './artifacts.css';

// Where artifacts are found: every generated document lives on the record it came from, in a Documents tab. It's made
// from the record's ••• menu or as part of an action, and a report's files come from the report's Export.

export default function WhereArtifacts() {
  return (
    <>
      <Demo wide caption="On the record: a Documents tab (1) lists every document made from Metro Fuels, newest first, with its type, who made it, and when. Generate (2) in the ••• menu makes a new one from the record as it is now.">
        <Frame on="Customers" overlay={<div className="ar-menu"><p>Download customer PDF</p><p className="on">Generate statement…</p><p>Generate contract…</p><p className="sep">Archive</p></div>}>
          <div className="as-a-page">
            <p className="as-crumb">Customers <span>/</span> <b>Metro Fuels</b></p>
            <div className="as-a-head">
              <div><p className="m-title">Metro Fuels</p><p className="as-meta"><Pill tone="bad">3 unpaid</Pill><span>Cebu · TIN 204-311-580-000</span></p></div>
              <span className="as-acts"><H n={2}><Btn kind="quiet">•••</Btn></H><Btn>Send statement</Btn><Btn kind="pri">New invoice</Btn></span>
            </div>
            <p className="as-a-tabs"><span>Overview</span><span>Invoices 38</span><span>Payments 61</span><H n={1}><span className="on">Documents 7</span></H></p>
            <div className="ar-docs">
              <p className="ar-doc"><i className="ar-type pdf">PDF</i><span><b>Notice of overdue balance</b><small>Generated by Liza · 28 Sep 2026, 9:20 AM · sent to Joy Santos</small></span><Pill>Delivered</Pill><a className="m-link">Download</a></p>
              <p className="ar-doc"><i className="ar-type pdf">PDF</i><span><b>Statement, September 2026</b><small>Generated by Ana · 28 Sep 2026, 9:14 AM · sent to Joy Santos</small></span><Pill>Delivered</Pill><a className="m-link">Download</a></p>
              <p className="ar-doc"><i className="ar-type pdf">PDF</i><span><b>Official receipt OR-CEB-0921</b><small>Issued by Ana · 18 Sep 2026 · ₱760,000.00 on INV-1038</small></span><Pill>Issued</Pill><a className="m-link">Download</a></p>
              <p className="ar-doc"><i className="ar-type docx">DOCX</i><span><b>Credit agreement, v2</b><small>Generated by Ramon · 12 Sep 2026 · edited, then signed</small></span><Pill tone="ok">Signed</Pill><a className="m-link">Download</a></p>
              <p className="ar-doc"><i className="ar-type pdf">PDF</i><span><b>Statement, August 2026</b><small>Generated by Ana · 1 Sep 2026 · sent to accounts@metrofuels.com</small></span><Pill tone="bad">Bounced</Pill><a className="m-link">Download</a></p>
              <p className="ar-doc"><i className="ar-type pdf">PDF</i><span><b>Invoice INV-1038</b><small>Issued by Ramon · 3 Aug 2026</small></span><Pill>Issued</Pill><a className="m-link">Download</a></p>
            </div>
          </div>
        </Frame>
      </Demo>

      <Section title="Where each kind is found">
        <When head={['Artifact', 'Made from', 'Found']} rows={[
          ['Invoice, receipt', 'Issuing the invoice, recording the payment', 'On the invoice or payment, and in the customer’s Documents'],
          ['Statement of account', 'Generate statement, or the monthly schedule', 'The customer’s Documents, and the email that sent it'],
          ['Contract, agreement', 'Generate contract, from the loan or customer', 'The loan’s Documents, each version kept'],
          ['A report as a file', 'Export, on the report', 'Downloaded at once when small; otherwise in Jobs'],
          ['A list or bulk data', 'Export, on the list', 'Jobs, as a download: see System jobs'],
        ]} />
      </Section>

      <div className="g-duo">
        <Section title="Guidelines">
          <Rules items={[
            ['Documents live on their record.', 'A Documents tab on every record that makes them, newest first.'],
            ['Generate from the record’s ••• menu.', 'Or as part of an action, such as Issue invoice. The document uses the record as it is now.'],
            ['Say what, who, and when.', 'Type, name, who made it, when, and where it went: sent to Joy Santos, signed.'],
            ['Keep every version.', 'A regenerated contract is v2. The old one stays, marked as replaced.'],
            ['Link back from the document.', 'Each document names its record and number, so a printout can be traced.'],
          ]} />
        </Section>
        <Section title="Avoid">
          <Avoid items={[
            ['A separate Documents section for everything.', 'People search one long list instead of opening the customer they’re working on.'],
            ['Generating from a blank form.', 'People retype what the record already knows, and the two drift apart.'],
            ['Files named document(3).pdf.', 'Nobody can tell which statement was sent, or when.'],
            ['Overwriting the old version.', 'The signed contract is gone, replaced by a draft nobody signed.'],
            ['Documents with no reference.', 'A printed statement can’t be matched to the customer or period it came from.'],
          ]} />
        </Section>
      </div>
    </>
  );
}
